FROM python:3.12-slim

WORKDIR /app

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     gcc \
#     libc-dev \
#     && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# COPY templates/ .

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

# Expose the Flask port
EXPOSE 5000

# Run the application binding to 0.0.0.0 so it is accessible outside the container
CMD ["flask", "run", "--host=0.0.0.0"]
